
[env]
TERM = "xterm-256color"

[font]
size = 14
normal.family = "CaskaydiaCove Nerd Font"

[window]
opacity = 1

[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 100
lines = 25

[general]
import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
