# AI
windowrule {
  name = "Automaticaly create group when Gemini opens"
  match:class = chrome-gemini.google.com__app-Default
  group = "always"
}

windowrule {
  name = "Automaticaly create group when ChatGPT opens"
  match:class = chrome-chatgpt.com__-Default
  group = "always"
}

windowrule {
  name = "Automaticaly create group when Claude opens"
  match:class = com.anthropic.Claude
  group = "always"
}

windowrule {
  name = "Automaticaly create group when Lovevoice opens"
  match:class = chrome-lovevoice.ai__-Default
  group = "always"
}

windowrule {
  name = "Automaticaly create group when Upscayl opens"
  match:class = Upscayl
  group = "always"
}
