# Open Apps on a specific workspace

# Web Browser
windowrule = workspace 1, match:class zen

# Terminal
windowrule = workspace 2, match:class com.mitchellh.ghostty
windowrule = workspace 2, match:class kitty
windowrule = workspace 2, match:class Alacritty

# Coding
windowrule = workspace 3, match:class code

# AI
windowrule = workspace 4, match:class chrome-gemini.google.com__app-Default
windowrule = workspace 4, match:class com.anthropic.Claude
windowrule = workspace 4, match:class chrome-chatgpt.com__-Default
windowrule = workspace 4, match:class chrome-lovevoice.ai__-Default
windowrule = workspace 4, match:class Upscayl

# File Explorer
windowrule = workspace 5, match:class thunar
windowrule = workspace 5, match:class org.gnome.Nautilus

# Gaming
windowrule = workspace 6, match:class steam

# Music
windowrule = workspace 7, match:class Spotify
windowrule = workspace 7, match:class chrome-music.youtube.com__-Default

# WhatsApp
windowrule = workspace 8, match:class chrome-web.whatsapp.com__-Default

# Discord
windowrule = workspace 9, match:class discord
