windowrule = workspace 2, match:class com.mitchellh.ghostty
windowrule = workspace 3, match:class resolve
windowrule = workspace 4, match:class chrome-gemini.google.com__-Default
windowrule = workspace 4, match:class claude-desktop
windowrule = workspace 4, match:class chrome-chatgpt.com__-Default
windowrule = workspace 5, match:class org.gnome.Nautilus
windowrule = workspace 6, match:class steam
windowrule = workspace 7, match:class Spotify
windowrule = workspace 7, match:class chrome-music.youtube.com__-Default
windowrule = workspace 8, match:class chrome-web.whatsapp.com__-Default
windowrule = workspace 9, match:class discord
