import = [
  "~/AppData/Roaming/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 18
normal.family = "MesloLGS Nerd Font Mono"

[window]
opacity = 1

[window.padding]
x = 5
y = 10

[window.dimensions]
columns = 100
lines = 25
